#ifndef INC_APP_CONFIG_H_
#define INC_APP_CONFIG_H_

#include <stdint.h>
#include "main.h"

/* ============================================================
 * 1. System clock
 * ============================================================
 * Timer clock frequency used by the timing and PWM conversion macros.
 *
 * The current project configuration uses a 72 MHz timer clock. If the
 * system clock tree or timer clock source is changed, this value must
 * be updated to keep the period and RPM calculations correct.
 */
#define CLK_FREQ                    72000000UL

/* ============================================================
 * 2. Hardware timer mapping
 * ============================================================
 * Centralized timer-handle mapping for the application modules.
 *
 * The htim1, htim2, and htim4 objects are generated by CubeMX in
 * main.c. The macros below provide module-level names for the timer
 * roles used by the application code.
 *
 * Current mapping:
 *   CONTROL_TIMER_HANDLE   -> TIM1 base timer for the control update flag.
 *   MOTOR_PWM_TIMER_HANDLE -> TIM2 PWM timer for ESC output.
 *   HALL_TIMER_HANDLE      -> TIM4 Hall sensor timer for capture and timeout.
 */
extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim4;

#define CONTROL_TIMER_HANDLE        htim1
#define MOTOR_PWM_TIMER_HANDLE      htim2
#define HALL_TIMER_HANDLE           htim4

#define MOTOR_PWM_CHANNEL           TIM_CHANNEL_2
#define HALL_CAPTURE_CHANNEL        TIM_CHANNEL_1

/* ============================================================
 * 3. Timer period calculation
 * ============================================================
 * Timer period calculation in milliseconds.
 *
 * Formula:
 *   period_ms = (PSC + 1) * (ARR + 1) / timer_clock * 1000
 *
 * TIMx_PSC and TIMx_CTR_PER are defined in main.h and are also used
 * by the CubeMX-generated timer initialization code in main.c. Keep
 * these values consistent with the actual timer configuration.
 */
#define TIM1_PER_MS                 \
    (1.0f / CLK_FREQ * (TIM1_PSC + 1) * (TIM1_CTR_PER + 1) * 1000.0f)

#define TIM2_PER_MS                 \
    (1.0f / CLK_FREQ * (TIM2_PSC + 1) * (TIM2_CTR_PER + 1) * 1000.0f)

#define TIM4_PER_MS                 \
    (1.0f / CLK_FREQ * (TIM4_PSC + 1) * (TIM4_CTR_PER + 1) * 1000.0f)

/* ============================================================
 * 4. Expected timer periods
 * ============================================================
 * Reference timer periods in milliseconds.
 *
 * These values are used by tim_per_check() to validate the configured
 * timer periods when that check function is called.
 *
 * Current expected timing:
 *   TIM1 = 10 ms   -> Control update period, approximately 100 Hz.
 *   TIM2 = 20 ms   -> ESC PWM period, approximately 50 Hz.
 *   TIM4 = 200 ms  -> Hall sensor timeout period.
 */
#define EXPECTED_TIM1_PER_MS        10.0f
#define EXPECTED_TIM2_PER_MS        20.0f
#define EXPECTED_TIM4_PER_MS        200.0f

/* ============================================================
 * 5. ESC PWM pulse width config
 * ============================================================
 * ESC PWM pulse-width limits and reference values.
 *
 * PWM_MIN_PULSEWIDTH, PWM_ZERO_PULSEWIDTH, and PWM_MAX_PULSEWIDTH
 * are expressed in milliseconds.
 *
 * PWM_US_MIN, PWM_US_NEUTRAL, MOTOR_MIN_START_US, and PWM_US_MAX
 * are expressed in microseconds and define the valid ESC command range.
 *
 * PWM conversion logic is implemented in motor_control.c.
 */
#define PWM_MIN_PULSEWIDTH          1.0f
#define PWM_ZERO_PULSEWIDTH         1.5f
#define PWM_MAX_PULSEWIDTH          2.0f

#define PWM_US_MIN                  1000
#define PWM_US_NEUTRAL              1500
#define MOTOR_MIN_START_US          1550
#define PWM_US_MAX                  2000

/* ============================================================
 * 6. RPM low-pass filter
 * ============================================================
 * First-order low-pass filter coefficient for RPM feedback.
 *
 * A smaller alpha produces smoother output with slower response.
 * A larger alpha produces faster response with more fluctuation.
 *
 * The RPM filter is initialized with this value in user_init(). The
 * filter update is performed in user_loop() when the control update
 * flag is set by the control timer.
 */
#define RPM_FILTER_ALPHA            0.05f

#endif /* INC_APP_CONFIG_H_ */
