#ifndef INC_APP_CONFIG_H_
#define INC_APP_CONFIG_H_

#include <stdint.h>
#include "main.h"

/* ============================================================
 * 1. System clock
 * ============================================================
 * Timer clock frequency used by the timing and PWM conversion macros.
 *
 * The current project configuration uses a 72 MHz timer clock. If the
 * system clock tree or timer clock source is changed, this value must
 * be updated to keep the period and RPM calculations correct.
 */
#define CLK_FREQ                    72000000UL

/* ============================================================
 * 2. Hardware timer mapping
 * ============================================================
 * Centralized timer-handle mapping for the application modules.
 *
 * The htim1, htim2, and htim3 objects are generated by CubeMX in
 * main.c. The macros below provide module-level names for the timer
 * roles used by the application code.
 *
 * Current mapping:
 *   CONTROL_TIMER_HANDLE   -> TIM1 base timer for the control update flag.
 *   MOTOR_PWM_TIMER_HANDLE -> TIM2 PWM timer for ESC output.
 *   HALL_TIMER_HANDLE      -> TIM3 Hall sensor timer for capture and timeout.
 */
extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim3;

#define CONTROL_TIMER_HANDLE        htim1
#define MOTOR_PWM_TIMER_HANDLE      htim2
#define HALL_TIMER_HANDLE           htim3

#define MOTOR_PWM_CHANNEL           TIM_CHANNEL_2
#define HALL_CAPTURE_CHANNEL        TIM_CHANNEL_1

/* ============================================================
 * 3. Timer period calculation
 * ============================================================
 * Timer period calculation in milliseconds.
 *
 * Formula:
 *   period_ms = (PSC + 1) * (ARR + 1) / timer_clock * 1000
 *
 * TIMx_PSC and TIMx_CTR_PER are defined in main.h and are also used
 * by the CubeMX-generated timer initialization code in main.c. Keep
 * these values consistent with the actual timer configuration.
 */
#define TIM1_PER_MS                 \
    (1.0f / CLK_FREQ * (TIM1_PSC + 1) * (TIM1_CTR_PER + 1) * 1000.0f)

#define TIM2_PER_MS                 \
    (1.0f / CLK_FREQ * (TIM2_PSC + 1) * (TIM2_CTR_PER + 1) * 1000.0f)

#define TIM3_PER_MS                 \
    (1.0f / CLK_FREQ * (TIM3_PSC + 1) * (TIM3_CTR_PER + 1) * 1000.0f)

/* ============================================================
 * 4. Expected timer periods
 * ============================================================
 * Reference timer periods in milliseconds.
 *
 * These values are used by tim_per_check() to validate the configured
 * timer periods when that check function is called.
 *
 * Current expected timing:
 *   TIM1 = 10 ms   -> Control update period, approximately 100 Hz.
 *   TIM2 = 20 ms   -> ESC PWM period, approximately 50 Hz.
 *   TIM3 = 200 ms  -> Hall sensor timeout period.
 */
#define EXPECTED_TIM1_PER_MS        10.0f
#define EXPECTED_TIM2_PER_MS        20.0f
#define EXPECTED_TIM3_PER_MS        200.0f

/* ============================================================
 * 5. ESC PWM pulse width config
 * ============================================================
 * ESC PWM pulse-width limits and reference values.
 *
 * PWM_MIN_PULSEWIDTH, PWM_ZERO_PULSEWIDTH, and PWM_MAX_PULSEWIDTH
 * are expressed in milliseconds and are used by the PWM-to-CCR
 * conversion macros.
 *
 * PWM_US_MIN, PWM_US_NEUTRAL, MOTOR_MIN_START_US, and PWM_US_MAX
 * are expressed in microseconds. The microsecond values are used by
 * the register interface and by motor_control_set_pwm_us().
 *
 * Current pulse-width convention:
 *   1000 us = Minimum valid pulse width.
 *   1500 us = Neutral pulse width.
 *   1550 us = Defined minimum start pulse threshold.
 *   2000 us = Maximum valid pulse width.
 */
#define PWM_MIN_PULSEWIDTH          1.0f
#define PWM_ZERO_PULSEWIDTH         1.5f
#define PWM_MAX_PULSEWIDTH          2.0f

#define PWM_US_MIN                  1000
#define PWM_US_NEUTRAL              1500
#define MOTOR_MIN_START_US          1550
#define PWM_US_MAX                  2000

/* ============================================================
 * 6. PWM frequency and CCR conversion
 * ============================================================
 * PWM frequency and compare-register conversion helpers for TIM2.
 *
 * PWM_FREQUENCY is derived from TIM2_PER_MS. With the current TIM2
 * configuration, the resulting PWM frequency is approximately 50 Hz.
 *
 * Conversion flow:
 *   pulse_width_ms -> duty ratio -> TIM2 CCR value
 *
 * PWM_US_TO_CCR(us) is the preferred application-level conversion
 * macro. It clamps the input pulse width to the configured ESC range,
 * converts microseconds to milliseconds, and then converts the result
 * to a TIM2 CCR value.
 */
#define PWM_FREQUENCY               \
    (1.0f / TIM2_PER_MS * 1000.0f)

#define PWM_PULSEWIDTH_TO_DUTYCYCLE(pulse_ms) \
    ((pulse_ms) / 1000.0f * PWM_FREQUENCY)

#define PWM_DUTYCYCLE_TO_CCR(duty)  \
    ((uint32_t)((duty) * TIM2_CTR_PER))

#define PWM_PULSEWIDTH_TO_CCR(pulse_ms) \
    PWM_DUTYCYCLE_TO_CCR(PWM_PULSEWIDTH_TO_DUTYCYCLE(pulse_ms))

#define PWM_US_TO_MS(us)            \
    ((float)(us) / 1000.0f)

#define PWM_US_CLAMP(us)            \
    (((us) < PWM_US_MIN) ? PWM_US_MIN : (((us) > PWM_US_MAX) ? PWM_US_MAX : (us)))

#define PWM_US_TO_CCR(us)           \
    ((uint32_t)PWM_PULSEWIDTH_TO_CCR(PWM_US_TO_MS(PWM_US_CLAMP(us))))

/* ============================================================
 * 7. Common PWM CCR values
 * ============================================================
 * CCR aliases for the configured minimum, neutral, and maximum PWM
 * pulse widths.
 *
 * These macros are not required by the current control flow, but they
 * are kept as convenient named constants for debugging or future use.
 */
#define PWM_CCR_MIN                 \
    PWM_PULSEWIDTH_TO_CCR(PWM_MIN_PULSEWIDTH)

#define PWM_CCR_DEFAULT             \
    PWM_PULSEWIDTH_TO_CCR(PWM_ZERO_PULSEWIDTH)

#define PWM_CCR_MAX                 \
    PWM_PULSEWIDTH_TO_CCR(PWM_MAX_PULSEWIDTH)

/* ============================================================
 * 8. Hall speed measurement
 * ============================================================
 * Hall sensor speed-measurement constants and conversion macro.
 *
 * HALL_EDGES_PER_REV:
 *   Number of Hall capture edges per mechanical revolution.
 *
 * HALL_CAPTURE_TO_RPM(capture_value):
 *   Converts a TIM3 capture interval count to motor speed in RPM.
 *
 * Calculation:
 *   edge_interval_s = capture_value * (TIM3_PSC + 1) / CLK_FREQ
 *   edge_frequency  = 1 / edge_interval_s
 *   motor_rpm       = edge_frequency * 60 / HALL_EDGES_PER_REV
 */
#define HALL_EDGES_PER_REV          12.0f

#define HALL_CAPTURE_TO_RPM(capture_value) \
    ((CLK_FREQ * 60.0f) / ((float)(capture_value) * (TIM3_PSC + 1) * HALL_EDGES_PER_REV))

/*
 * RPM value derived from the maximum TIM3 counter period.
 *
 * The Hall sensor module currently uses this value as a startup
 * fallback when the first capture occurs while the stored RPM feedback
 * is still zero.
 */
#define MIN_MOTOR_RPM               \
    HALL_CAPTURE_TO_RPM(TIM3_CTR_PER)

/* ============================================================
 * 9. RPM low-pass filter
 * ============================================================
 * First-order low-pass filter coefficient for RPM feedback.
 *
 * A smaller alpha produces smoother output with slower response.
 * A larger alpha produces faster response with more fluctuation.
 *
 * The RPM filter is initialized with this value in user_init(). The
 * filter update is performed in user_loop() when the control update
 * flag is set by the control timer.
 */
#define RPM_FILTER_ALPHA            0.05f

#endif /* INC_APP_CONFIG_H_ */
